README.md
example.js
index.js
test.js

JSON by default does not support RegExp objects or strings, I propose to add `RegExp` type to the schema types.
```js
reg: {
type: 'RegExp'
}
```
In this way *fast-json-stringify* will transform regex object in escaped strings and not in `'{}'` as *JSON.stringify* does.
Example:
```js
// Before
/"([^"]|\\")*"/
// After
'"\\"([^\\"]|\\\\\\\\\\")*\\""'
// Then
/"([^"]|\\")*"/.source === new RegExp(JSON.parse('"\\"([^\\"]|\\\\\\\\\\")*\\""')).source // true
```
What do you think?

Regex stringify proposal

---

example.js
index.js
test.js

Added `required` field support.
Example:
```javascript
const fastJson = require('fast-json-stringify')
const stringify = fastJson({
title: 'schema with required field',
properties: {
str: {
type: 'string',
required: true
},
num: {
type: 'number'
}
}
})
```
If the required field is not provided, `fast-json-stringify` will throw an error.
Required feedback 😄

Required fields support

---

README.md
index.js
test.js

Using example.js as schema, this is the generated code:
```javascript
function $main(obj) {
var json = '{'
if (obj.firstName !== undefined) {
json += '"firstName":'
json += $asString(obj.firstName)
json += ','
}
if (obj.lastName !== undefined) {
json += '"lastName":'
json += $asString(obj.lastName)
json += ','
}
if (obj.age !== undefined) {
json += '"age":'
json += $asNumber(obj.age)
json += ','
}
if (obj.now !== undefined) {
json += '"now":'
json += $asString(obj.now)
json += ','
} else {
throw new Error('now is required!')
}
if (obj.reg !== undefined) {
json += '"reg":'
json += $asString(obj.reg)
}
json += '}'
return json
}
```
If a parameter is required, there will be the `else` branch.
As you can see I'm not using `obj.hasOwnProperty(prop)` for testing the existence of the key (is …

Support for missing parameters

---

README.md
example.js
index.js
test.js

Updated required field according to the json schema spec.
Moving from:
```javascript
...
field: {
type: 'string',
required: true
}
...
```
to:
```javascri
...
field: {
type: 'string'
}
},
required: ['field']
...
```
[Here](http://json-schema.org/example1.html) some official example.

Fix required field

---

README.md
example.js
index.js
package.json
test/additionalProperties.test.js

Added support for `additionalProperties`.
See discussion in #5.
*Ps: I took the occasion to add a table of contents to the docs.*

Additional properties support

---

README.md
index.js
test/ref.json
test/ref.test.js

As titled.
This implementation supports both *internal* and *external* definitions.
**Caveats:**
If the user is using an external json file for his definitions it must use `__dirname` to get the correct path.
See the following example (the same of the test).
```javascript
const schema = {
title: 'object with $ref',
properties: {
obj: {
$ref: __dirname + '/ref.json#/definitions/def'
}
}
}
```
If everything is ok to you I can update the docs.

$ref support

---

index.js

This reverts commit 1a63b7c1ff8b065da5f37f18d3440e0e92b97a31.
Fixes #17

Revert "Replaced asString with JSON.stringify"

---

index.js

I've applied the @addaleax's suggestions (#23) and we got a sensible increase of the performances in string serialization! :)
Before
```
JSON.stringify short string x 5,045,063 ops/sec ±1.14% (88 runs sampled)
fast-json-stringify short string x 11,559,636 ops/sec ±0.82% (90 runs sampled)
```
After
```
JSON.stringify short string x 5,088,404 ops/sec ±0.79% (92 runs sampled)
fast-json-stringify short string x 12,171,333 ops/sec ±0.75% (90 runs sampled)
```
Nice catch @addaleax! :)
cc @mcollina

Faster string serialization

---

index.js
test/basic.test.js

I tried this:
```diff
diff --git i/index.js w/index.js
index ff80f46..923d310 100644
--- i/index.js
+++ w/index.js
@@ -306,7 +306,7 @@ function buildObject (schema, code, name, externalSchema, fullSchema) {
// Using obj.key !== undefined instead of obj.hasOwnProperty(prop) for perf reasons,
// see https://github.com/mcollina/fast-json-stringify/pull/3 for discussion.
code += `
-      if (obj.${key} !== undefined) {
+      if (obj['${key}'] !== undefined) {
json += '${$asString(key)}:'
`
@@ -392,6 +392,7 @@ function nested (laterCode, name, key, schema, externalSchema, fullSchema) {
var code = ''
var funcName
const type = schema.type
+  const value = `obj['${key.substring(1)}']`
switch (type) {
case 'null':
code += `
@@ -400,36 +401,36 @@ function nested (laterCode, name, key, schema, …
```

Allow non alpha keys

---

README.md
bench.js
index.js
package.json
test/basic.test.js

@mcollina Something like this you had in mind?

Add ability to uglify generated code

---

index.js
test/missing-values.test.js

As titled, see #40 for more info.
`undefined` is not handled because of [this](https://github.com/fastify/fast-json-stringify/blob/master/index.js#L351).

Handle null when value should be string

---

index.js
test/array.test.js

JSON Schema provides support for [tuple validation](https://spacetelescope.github.io/understanding-json-schema/reference/array.html#tuple-validation); however, this module previously lacked support for it.
This commit will allow arrays to either be of a single type or to be of mixed types in the order specified by the schema.

fix(buildArray): Support tuple arrays

---

index.js
test/array.test.js

Fixes #44 
The problem with the repeated items in the stringified array was actually repeated types in the items array, not `patternProperties` specifically.
I have also updated the array item builder to throw an exception if the item in the array does not match the schema's definition. This resolves the problem with empty array items, e.g.
`[,{"foo":"1","bar":"foo"}]`

fix(build): Correctly handle repeated array types

---

index.js
package.json
test/anyof.test.js

Adds anyOf support

---

.gitignore
.travis.yml
index.js
test/additionalProperties.test.js
test/basic.test.js
test/patternProperties.test.js

Validate schema

---

index.js
test/basic.test.js

This PR fixes an error being thrown when building a stringify function from a schema with a property of type object whose key contains spaces:
```
SyntaxError: Unexpected token in
at Function (<anonymous>)
at build (/fast-json-stringify/index.js:104:20)
...
```
The error is thrown because the `nested()` function generates function names containing spaces.

Fix error being thrown because of spaces in key

---

README.md

Hey there, thanks for building this! Noticed a few sentences with awkward syntax or grammar in the readme. Went through and touched it up.

Edit grammar and syntax in readme

---

index.js
test/ref.test.js

This adds tests + a fix for #60 by adding a check to make sure there is a hash before doing the walk.

Fix #60, root references requiring a hash

---

index.js
test/additionalProperties.test.js
test/basic.test.js
test/long.test.js
test/required.test.js

This is an alternative to #69. Instead of throwing, it skips.
**master**:
```
JSON.stringify array x 3,379 ops/sec ±2.12% (86 runs sampled)
fast-json-stringify array x 6,406 ops/sec ±2.28% (84 runs sampled)
fast-json-stringify-uglified array x 6,283 ops/sec ±2.68% (83 runs sampled)
JSON.stringify long string x 9,841 ops/sec ±2.10% (86 runs sampled)
fast-json-stringify long string x 9,857 ops/sec ±2.14% (85 runs sampled)
fast-json-stringify-uglified long string x 9,862 ops/sec ±1.99% (85 runs sampled)
JSON.stringify short string x 4,071,077 ops/sec ±1.99% (83 runs sampled)
fast-json-stringify short string x 22,269,979 ops/sec ±2.17% (80 runs sampled)
fast-json-stringify-uglified short string x 23,330,578 ops/sec ±1.87% (85 runs sampled)
JSON.stringify obj x 1,670,370 ops/sec ±1.83% (86 …
```

skip non-coerceable numbers

---

README.md
index.js
package.json

As titled. We removed it from fastify long ago anyway.

Removed fast-safe-stringify, use plain JSON.stringify.

---

index.js
package.json
test/integer.test.js

After updating to version 1, I encountered an "isLong is not defined" error. I figured that was because I am not using the long package and it isn't installed at all in my package. Here is a little example to illustrate the problem.
```js
const fastJson = require('fast-json-stringify');
fastJson({
"properties": {
"x": {
"type": "integer"
}
},
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object"
})({ x: 2 });
```
Running that code will trigger the error.
I fixed the problem by extracting the checks for `isLong` from the generated code. I'm not entirely sure if that's the way it should be done, but I can imagine that it will also bring some little speed improvements as it does not insert if statements anymore which are going to fail anyway.
Please let me know if you want …

fix "isLong is not defined" error

---

index.js
test/typesArray.test.js

Fixes #77.
This adds support for `type` to be an array of types, e.g.
```json
{
"type": "object",
"properties": {
"stringOrNumber": {"type": ["string", "number"]}
}
}
```
Support of multiple types in tuple definitions is still missing. This probably requires some refactoring of the `buildArray()` function. Nevertheless, I have prepared already a test case for tuples (currently commented out).
I don't particularly like the implementation of `hasArrayOfTypes()`, so please let me know if you have any better ideas.

Add support for array of types in schema definition

---

index.js
test/nestedObjects.test.js

This fixes the serialization of nested objects when the contain the same properties as the parent, but use additionalProperties or patternProperties. Fixes #79.
**Benchmark before**
```
JSON.stringify array x 4,626 ops/sec ±0.36% (95 runs sampled)
fast-json-stringify array x 8,244 ops/sec ±0.66% (90 runs sampled)
fast-json-stringify-uglified array x 8,290 ops/sec ±0.51% (88 runs sampled)
JSON.stringify long string x 17,645 ops/sec ±0.36% (96 runs sampled)
fast-json-stringify long string x 17,400 ops/sec ±0.95% (94 runs sampled)
fast-json-stringify-uglified long string x 17,371 ops/sec ±1.10% (93 runs sampled)
JSON.stringify short string x 5,758,694 ops/sec ±0.15% (94 runs sampled)
fast-json-stringify short string x 32,446,046 ops/sec ±0.35% (96 runs sampled)
fast-json-stringify-uglified …
```

Fix serialization of nested objects

---

index.js
test/typesArray.test.js

I was trying to add response schemas to a production app using nullable dates and fastify. I noticed that type arrays would not work with string for dates while it worked fine when not using type arrays.
```javascript
{                                                                  
type: 'object',                                                 
properties: {                                                  
date: { type: 'string' }                                  
}                                                            
}
```
works for dates and will produce
```javascript
function $main(obj) {
var json = '{'
var addComma = false
if (obj['date'] !== undefined) {
if (addComma) {
json += ','
}
addComma = true
json += '"date":'
json += $asString(obj['date'])
}
json += '}'
return …
```

string type arrays handling dates

---

index.js
test/defaults.test.js

Implement https://github.com/fastify/fast-json-stringify/issues/87
The jsonschema can define `default` is the property is not given. This PR implements that feature.

Implement default key

---

README.md

Add default doc in README

---

index.js
package.json
test/if-then-else.test.js

Implement if/then/else

---

bench.js
index.js

We cache a module-wide Ajv instance instead of creating a new one
to validate each schema and then throw it away.

speed up creation time by 100x.

---

index.js
test/clean-cache.test.js

Fixes https://github.com/fastify/fastify/issues/922.
I'll open a pr also in Fastify to test this behavior.
[Ajv docs](https://github.com/epoberezkin/ajv#removeschemaobject-schemastring-keystring-refregexp-pattern---ajv) for reference.

Removed all cached schemas

---

bench.js
index.js
test/typesArray.test.js

Remove ajv for multiple type handling.
The removal of ajv was not related with this fix but its need is showcased by the edited benchmark.
Before:
```
JSON.stringify obj x 1,624,624 ops/sec ±0.72% (91 runs sampled)
fast-json-stringify obj x 729,975 ops/sec ±0.96% (92 runs sampled)
fast-json-stringify-uglified obj x 730,695 ops/sec ±0.73% (93 runs sampled)
```
After:
```
JSON.stringify obj x 1,638,558 ops/sec ±1.08% (91 runs sampled)
fast-json-stringify obj x 6,023,692 ops/sec ±0.82% (92 runs sampled)
fast-json-stringify-uglified obj x 5,895,250 ops/sec ±0.91% (93 runs sampled)
```

Fix object and null possible type handling.

---

index.js
package.json
test/allof.test.js

Add proper handling with nested allOf-s.
Closes: https://github.com/fastify/fastify/issues/1045

fix: fix nested allOf handling

---

index.js
test/if-then-else.test.js

This fixes the serialization of if-then-else schema when contains nested structure like array of objects

Fix if-then-else when contains nested structure

---

index.js
test/unknownFormats.test.js

Resolves #115 
This allows schemas that may have custom formats to be used.
As part of this change I've disabled warning log messages as when setting
`unknownFormats: "ignore"` warning messages are emitted everytime a schema
with unknown formats is compiled.
I have not disabled standard or error log messages.

feat: ignore unknown formats when compiling schemas

---

index.js
test/toJSON.test.js

Not sure if this is the way to go, but I didn't have any other idea how to accomplish the behavior. If you have any suggestions how to do this differently please share your idea!
**Node 10.9.0**
```js
FJS creation x 7,423 ops/sec ±2.95% (92 runs sampled)
JSON.stringify array x 4,588 ops/sec ±1.22% (93 runs sampled)
fast-json-stringify array x 7,248 ops/sec ±0.40% (92 runs sampled)
fast-json-stringify-uglified array x 7,262 ops/sec ±0.44% (92 runs sampled)
JSON.stringify long string x 17,338 ops/sec ±0.26% (95 runs sampled)
fast-json-stringify long string x 17,267 ops/sec ±0.37% (94 runs sampled)
fast-json-stringify-uglified long string x 17,298 ops/sec ±0.34% (95 runs sampled)
JSON.stringify short string x 4,879,163 ops/sec ±0.29% (93 runs sampled)
fast-json-stringify short string x …
```

call toJSON method on object types

---

index.js
test/if-then-else.test.js

The two functions created by fast-json-stringify to serialize the object throws with:
_Identifier * has already been declared_
when if-then-else statements is in a deep object structure

fix if-then-else with deep nested structure

---

.gitignore
.travis.yml
index.js
package.json
test/inferType.test.js
test/json-schema-test-suite/README.md
test/json-schema-test-suite/draft4.test.js
test/json-schema-test-suite/draft4/required.json
test/json-schema-test-suite/draft6.test.js
test/json-schema-test-suite/draft6/required.json
test/json-schema-test-suite/draft7.test.js
test/json-schema-test-suite/draft7/required.json
test/json-schema-test-suite/util.js

This PR will add basic support to test against the official https://github.com/json-schema-org/JSON-Schema-Test-Suite. It contains only tests for the `required` feature.

basic support to test against official JSON-Schema-Test-Suite

---

index.js
package.json
test/anyof.test.js

`anyOf` used with both a type `object` and `array` fails to serialize either of the type since the serialization functions are named the same. I added a prefix to the array one but I'm not sure it's the right way to go, if you have a better suggestion I can change.

Fix serialization of anyOf with both array and object types

---

README.md
index.js
test/toJSON.test.js

Support of the `nullable` option of ajv (Open API 3 specification) on object.
An object declared nullable can have a null value.
Today, a null object stringified lead to this error: 
```javascript
TypeError: Cannot read property 'toJSON' of null
```
As described [in the issue #130](https://github.com/fastify/fast-json-stringify/issues/130)

Better support for `null` values (#130)

---

index.js
test/surrogate.test.js

I changed $asStringSmall function so It can detect surrogate character.
But in surrogate.test.js if you uncomment line 50 and 65 , test will fail.
I am using node 11.12.0.
Is JSON.Stringify() is up to date or what @mathiasbynens has said in issue 147 is in test phase?

well formed unicode string (#147)

---

README.md

I've also adjust some of the whitespacing at the end.. you know, a bit of OCD.

Added a note regarding the use of new Function()

---

bench.js
package.json

_Note: The `json-strify` does not validate, just stringifies, `json-strify` is made for users who don't want write schemas and direct replacement to `JSON.stringify` for little extra performance`_

[Benchmark]: Add more similar library to benchmark

---

index.js
test/anyof.test.js

Would it be possible to add a check for null values in this function?  The `in` operator is causing an error when `null` is found in the schema.  For example:
```javascript
response: {
200: {
description: 'Success',
type: 'string',
nullable: true
enum: [null] 
}
}
```
With JSON Schema, one could use `type: 'null'`, but I have a requirement to only use OAS 3.0 features, so I can't change the schema to use `type: 'null'`.

Check for null value before using `in`.

---

README.md
bench.js
index.d.ts
index.js
package.json
test/array.test.js
test/basic.test.js
test/defaults.test.js
test/if-then-else.test.js
test/inferType.test.js
test/types/test.ts

As far as I understand the issue #97, uglify-es was added to improve throughput in Node.js 6 which is [EOL](https://github.com/nodejs/Release#end-of-life-releases) nowadays and I guess it can be safety dropped now.
One more point to drop support is that uglify-es is [no longer maintained](https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058)
Closes #97

Dropped uglifier support

---

README.md
index.js
test/ref.test.js

PR to implement #187:
Tests all pass. Benchmark results:
```
FJS creation x 52,630 ops/sec ±1.80% (89 runs sampled)
JSTR creation x 131,478 ops/sec ±0.73% (90 runs sampled)
CJS creation x 135,084 ops/sec ±1.18% (95 runs sampled)
JSON.stringify array x 4,790 ops/sec ±0.36% (95 runs sampled)
fast-json-stringify array x 7,638 ops/sec ±1.75% (88 runs sampled)
fast-json-stringify-uglified array x 8,054 ops/sec ±1.22% (96 runs sampled)
json-strify array x 80,063,937 ops/sec ±0.88% (95 runs sampled)
compile-json-stringify array x 7,661 ops/sec ±1.37% (92 runs sampled)
JSON.stringify long string x 13,349 ops/sec ±1.23% (88 runs sampled)
fast-json-stringify long string x 13,721 ops/sec ±0.64% (96 runs sampled)
fast-json-stringify-uglified long string x 13,727 ops/sec ±1.18% (91 runs sampled) …
```

Support nested $ref-erences

---

index.js
test/ref.test.js

The following case I have met in fastify-swagger - the following reference is not working in fields, where fast-json-stringify is used, but works fine with ajv parser.
```
const fastJsonStringify = require('fast-json-stringify')
fastJsonStringify(
{ type: 'object',
description: 'test',
properties: { param: { $ref: '#/definitions/test' } } },
{ schema: { '#/definitions/test': { type: 'string' } } }
)
```
With version 1.15.6 it raises following error:
```
return schema['definitions']['test']
^
TypeError: Cannot read property 'test' of undefined
```
- tests
```
$ npm run test
> fast-json-stringify@1.15.6 test /home/mgolovanov/work/pulls/fast-json-stringify
> npm run test:lint && npm run test:unit && npm run test:typescript
> fast-json-stringify@1.15.6 test:lint …
```

Fix relative ref resolving issue

---

README.md
index.js
package.json
test/bigint.js
test/integer.test.js

Added BigInt support

---

index.js
package.json
test/ref.test.js

Hello folks!
Typos are a significant pain point in programming, especially with JSON schemas.
This pr introduces a better debugging experience to help the user figure out what's going wrong.
To improve the experience even further, I've used [string-similarity](https://github.com/aceakash/string-similarity), a library that uses the Dice's Coefficient to figure out if two strings are similar. I think this approach can be reused in Fastify as well.

 Improve the debugging experience in case of a bad reference

---

README.md
index.js
test/additionalProperties.test.js
test/patternProperties.test.js

In some cases, the order of the keys is important, it might be for readability or other reasons. With the current implementation, every additional property is added at the beginning of the json, making it very hard to guarantee the order of the keys if you don't know them in advance.
This pr fixes this and serialize additional/pattern properties at the end of a json string.
Not sure if we should consider this a breaking change, as usually people test their code with `JSON.parse`.

Serialize additional properties at the end of the json

---

index.js
test/anyof.test.js

Fixing and adding refs in anyOf https://github.com/fastify/fast-json-stringify/issues/189

adding dereference of refs in anyOfs

---

index.js
test/ref.test.js

Was getting the error `Cannot find reference 'definitions'` and it is because the `schema` variable is replaced on line 80, so the original schema definition is lost.
Adding results of benchmark run:
```
FJS creation x 45,686 ops/sec ±2.46% (80 runs sampled)
JSTR creation x 122,116 ops/sec ±1.14% (89 runs sampled)
CJS creation x 123,350 ops/sec ±1.10% (91 runs sampled)
JSON.stringify array x 3,565 ops/sec ±2.88% (83 runs sampled)
fast-json-stringify array x 5,443 ops/sec ±2.29% (81 runs sampled)
fast-json-stringify-uglified array x 5,363 ops/sec ±2.79% (79 runs sampled)
json-strify array x 49,040,148 ops/sec ±1.25% (91 runs sampled)
compile-json-stringify array x 5,675 ops/sec ±2.28% (82 runs sampled)
JSON.stringify long string x 12,497 ops/sec ±1.91% (86 runs sampled)
fast-json-stringify …
```

pass full schema to buildObject if $ref is defined at the top level

---

index.js
test/oneof.test.js

Working on fastify schemas I found that it lacks support for `oneOf`. I tried both, writing manually the schema and using fluent and typebox. 
```
FastifyError [FST_ERR_SCH_BUILD]: FST_ERR_SCH_BUILD: Failed building the schema for GET: /api/v1/channels, due error undefined unsupported
at Object.afterRouteAdded (/Users/maksim/Projects/evologi/orderpod-backend/node_modules/fastify/lib/route.js:239:37)
at /Users/maksim/Projects/evologi/orderpod-backend/node_modules/fastify/lib/route.js:160:29
at Object._encapsulateThreeParam (/Users/maksim/Projects/evologi/orderpod-backend/node_modules/avvio/boot.js:422:7)
at Boot.callWithCbOrNextTick (/Users/maksim/Projects/evologi/orderpod-backend/node_modules/avvio/boot.js:344:5)
at Boot._after (/Users/maksim/Projects/evologi/orderpod-backend/node_modules/ …
```

Adds support for oneOf schemas

---

index.js
test/basic.test.js
test/date.test.js

serializing null value crash fix

---

index.js
test/array.test.js
test/basic.test.js

This PR closes https://github.com/fastify/fast-json-stringify/issues/227
So tests pass but I couldn't get the typescript part passing, but I didn't touch that part so I thought it might just be my machine or something.

Handle object property starting with `@` when the property is an array or object

---

README.md

Clarified the language of the security notifce.

Improved security notice

---

index.js
test/array.test.js

Makes sure when `Array`s don't explicitly specify items - they'll have `any` type
Fixes #204

Implicit any type for array items

---

index.js
test/anyof.test.js

I don't think #230 is technically an issue, I think it's just how AJV's `properties` validation keyword works.
Assume we have this schema:
```js
{
title: 'type array that may have any of declared items',
type: 'array',
items: {
anyOf: [
{
properties: {
savedId: {
type: 'string'
}
}
},
{
properties: {
error: {
type: 'string'
}
}
}
]
}
}
```
and test array:
```js
[{ savedId: 'great' }, { error: 'oops' }]
```
If we `build` the schema it'll correctly precompile it with the following `validate` calls to AJV:
but AJV's docs on `properties` say:
> properties keyword does not require that the properties mentioned in it are present in the object
> -- https://ajv.js.org/keywords.html#properties
Because of that:
- first `ajv.validate` call matches any object
- only …

Adds test case for anyOf with multiple array items

---

index.js
test/anyof.test.js
test/oneof.test.js
test/ref.test.js

This PR is intended to fix https://github.com/fastify/fast-json-stringify/issues/238.
The problem in the current implementation is that relative JSON pointers in `$ref`s like `#/definitions/def` always search in the main schema, even if the `$ref` is found in an external schema.
With this change the code will keep track of the current parent (or "context", if you will) so that subsequent `$ref`s will search in the appropriate schema.
There was an original attempt to fix this in https://github.com/fastify/fast-json-stringify/pull/185/files, but that was limited to some special conditions (i.e. only in object properties).
Also the assumptions in https://github.com/fastify/fast-json-stringify/pull/185/files#diff-168726dbe96b3ce427e7fedce31bb0bcR537 about existence of `schema.definitions` is …

Fix relative json paths in external schema

---

index.js

Because calling `+=` operand is cost effective, reducing the number of calls seems like a good move to improve performances.
Reference benchmark
```
FJS creation x 36,866 ops/sec ±3.36% (74 runs sampled)
JSTR creation x 103,618 ops/sec ±3.28% (78 runs sampled)
CJS creation x 110,871 ops/sec ±2.26% (85 runs sampled)
JSON.stringify array x 3,308 ops/sec ±3.92% (79 runs sampled)
fast-json-stringify array x 5,923 ops/sec ±1.13% (86 runs sampled)
json-strify array x 48,848,583 ops/sec ±0.61% (91 runs sampled)
compile-json-stringify array x 6,132 ops/sec ±1.49% (85 runs sampled)
JSON.stringify long string x 13,234 ops/sec ±0.48% (93 runs sampled)
fast-json-stringify long string x 13,205 ops/sec ±0.44% (92 runs sampled)
json-strify long string x 250,959 ops/sec ±1.04% (91 runs sampled) …
```

fix: avoid unecessary concat calls

---

index.js
test/typesArray.test.js

and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.

fix: passing null object to type array defaults to empty array (#249)

---

index.js
test/anyof.test.js

This PR updates the `anyOf` code generation pass to omit Symbol properties for the AJV validation schema. This is done via `JSON.stringify()` which will automatically omit Symbols (and other non-JSON applicable types). This replaces the previous approach that used NodeJS's `util.inspect()`.
Fixes https://github.com/fastify/fast-json-stringify/issues/271.

Omit Symbol properties for anyOf validation schema

---

index.js
test/const.test.js

Adds support for `const` keyword
Fixes #275 
References: http://json-schema.org/understanding-json-schema/reference/generic.html#id5

feat: add support for const value

---

index.js
test/array.test.js

This PR follows on from PR https://github.com/fastify/fast-json-stringify/pull/272. It removes the last call to `util.inspect()` and leverages `JSON.stringify()` instead to omit all non-json and non-jsonschema properties in the `fast-json-stringify` codegen pass. This allows callers to add non-json metadata (with particular note to `Symbol` properties) to their schemas which will be ignored once passed to the `fast-json-stringify` API.

Fix: Omit all Non-JSON schema applicable properties from codegen (#279)

---

bench.js
index.js
test/basic.test.js

This PR fixes the linting warnings across the codebase to resolve issue #281. It replaces `var` for `let` and `const` where appropriate. 
Note: The majority of the replacements were fairly straightforward, however I did spot a possibly `undefined` condition on line [621](https://github.com/sinclairzx81/fast-json-stringify/blob/master/index.js#L620-L623) with respect to the variable `walk`. You may wish to double check the additional `ref` check I've added on this code path.

chore: resolve linting rules | let & const (#281)

---

README.md
index.d.ts
index.js
test/integer.test.js
test/types/test.ts

Fix #277 
Note that to implement a `rounding` input option the most straightforward way is to generate the output function calling a global named function.
```js
let customAsInteger = $asInteger.toString()
if (options.rounding) {
customAsInteger = customAsInteger.replace('parseInt', options.rounding)
}
```
In this case the input would be the ugly (note the Math.round as 'string`):
```
const debugCompiled = fastJson(schema, { debugMode: true, rounding: 'Math.round' })
```
Or:
```
function round(in){ return Math.round(in) }
const debugCompiled = fastJson(schema, { debugMode: true, rounding: round })
```
Where
```diff
-  customAsInteger = customAsInteger.replace('parseInt', options.rounding)
+ customAsInteger = customAsInteger.replace('parseInt', options.rounding.name)
```
Which one do you …

add float truncation

---

index.d.ts
index.js
test/any.test.js

This PR adds support for empty `{}` `any` schemas to resolve issue #255. This update checks for the existence of a `type` property on the schema, and if not found, defaults to a `JSON.stringify()` for serialization. 
Have added a few tests to `any.test.js` and updated `index.d.ts` accordingly. Submitting this PR for review. 
```
cpu  AMD Ryzen 7 3700X 8-Core Processor
ram  32GB 
node v12.18.2
FJS creation x 56,104 ops/sec ±0.26% (92 runs sampled)
CJS creation x 162,430 ops/sec ±0.27% (98 runs sampled)
JSON.stringify array x 3,320 ops/sec ±0.33% (91 runs sampled)
fast-json-stringify array x 8,465 ops/sec ±0.37% (90 runs sampled)
compile-json-stringify array x 7,756 ops/sec ±0.75% (94 runs sampled)
JSON.stringify long string x 10,028 ops/sec ±0.17% (95 runs sampled)
fast-json-stringify long …
```

Support for empty schemas #255

---

index.js
test/additionalProperties.test.js

This PR should resolve issue https://github.com/fastify/fast-json-stringify/issues/293. It carries out additional `type === undefined` checks on the `additionalProperties: {}` code path resolving to `$asAny` in these cases. This enables support for empty `additionalProperties: {}` schemas.
The check on line 543 was all that was necessary to resolve this issue. The preceding check on line 445 was added as `$asAny` seemed appropriate (both code paths are virtually identical), however I've not implemented any specific tests for this code path as I'm not certain what conditions trigger it. Feel free to remove if necessary.
```
FJS creation x 55,526 ops/sec ±0.32% (95 runs sampled)
CJS creation x 157,538 ops/sec ±0.36% (92 runs sampled)
JSON.stringify array x 3,709 ops/sec ±0.22% (94 runs …
```

Fix: Support for empty schemas in additionalProperties

---

index.js
package.json
test/side-effect.test.js

fix: avoid side effect per oneOf and anyOf

---

index.js
test/additionalProperties.test.js

Fixes https://github.com/fastify/fast-json-stringify/issues/299
Basically `JSON.stringify` doesn't work for Functions and Symbols, and results in `undefined`, which is invalid JSON: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description
So instead, when dealing with additionalProperties, make sure we aren't trying to serialize symbols or functions.
```
[13:26] (fix-serializing-undefined) fast-json-stringify $ yarn run test
yarn run v1.22.4
$ npm run test:lint && npm run test:unit && npm run test:typescript
> fast-json-stringify@2.5.0 test:lint repos/fast-json-stringify
> standard
> fast-json-stringify@2.5.0 test:unit repos/fast-json-stringify
> …
```

Fix creation of invalid JSON when serializing functions or symbols (#299)

---

index.js
test/ref.test.js

Regression of https://github.com/fastify/fast-json-stringify/pull/302

fix: ajv is not defined when oneOf/allOf in external schema

---

index.js
test/requiresAjv.test.js

This resolves https://github.com/fastify/fastify/issues/2990
I am _guessing_ that an AJV instance isn't passed to every validator as a memory optimization technique. Frankly, I think that's a bit extreme. I think it would be far simpler to rip out the `dependsOnAjv` check and simply:
```js
const dependencies = [new Ajv(options.ajv]
const dependenciesName = ['ajv']
dependenciesName.push(code)
```
But I didn't do that. Instead I added a new conditional check in the `dependsOnAjv` function. While I was at it, I split the regular expression up into its constituent parts. I had a really difficult time seeing the `|` operators in the expression, and it's clear this is just going to continue to grow.

Fastify issue 2990

---

index.js

As discussed in https://github.com/fastify/fast-json-stringify/pull/316#issuecomment-817168902, this PR removes the expensive depends on AJV check.

Remove ajv check

---

index.js
test/enum.test.js

@mcollina @Eomm 
As mentioned in https://github.com/fastify/fast-json-stringify/issues/274, I just revert the changes of https://github.com/fastify/fast-json-stringify/pull/254 and everything works, the test cases introduced in 254 and the case mentioned in the issue (I also added it in the enum.test.js).
Anyway, I don't know if I missed something, or better, why enum was introduced as object keywords.

handle enum property when type is not specified

---

index.js

Moving the `if else if` chain to `switch` and adding an `else` statement in the `addComa` function seems to have a slightly improvement on the speed.
Before
```
FJS creation x 5,192 ops/sec ±1.50% (89 runs sampled)
CJS creation x 148,523 ops/sec ±1.81% (90 runs sampled)
JSON.stringify array x 3,917 ops/sec ±2.35% (91 runs sampled)
fast-json-stringify array x 7,702 ops/sec ±2.08% (88 runs sampled)
compile-json-stringify array x 6,930 ops/sec ±1.72% (87 runs sampled)
JSON.stringify long string x 12,647 ops/sec ±0.89% (90 runs sampled)
fast-json-stringify long string x 12,895 ops/sec ±0.18% (98 runs sampled)
compile-json-stringify long string x 12,874 ops/sec ±0.32% (97 runs sampled)
JSON.stringify short string x 10,725,098 ops/sec ±1.75% (93 runs sampled)
fast-json-stringify short string x …
```

Minor speed improvements

---

index.js
test/date.test.js
test/integer.test.js

Fixes #333 (I think?)
Hi, I tried to fix the problem in #333 by removing the default value introduced by @Eomm  [here](https://github.com/fastify/fast-json-stringify/pull/278/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R250).
I've added a few more tests and all _seems_ to be ok but I'm not sure this is the right approach as it's the first time I've taken a look at this library.
#332 calls `asInteger` instead of `Number` but `asInteger` has a fallback case that will inevitably convert a null value to 0. Removing that line fixes the issue and at the same time the tests in #332 (as a well as a few more added by me) also pass but again, I'm afraid some situations could …

Attempt to fix 333

---

index.js
package.json
test/webpack.test.js

When running the code through a minimizer (e g through Webpack/Terser),
the minimizer renames functions such as "$asBoolean". However, when the
function is called, it's hard coded as the string "$asBoolean", so the
generated code fails with "$asBoolean is not defined".
Make sure that the original $asBoolean function is included, and not
a renamed version of it, by making $asBoolean and friends string constants.
Fixes: https://github.com/fastify/fast-json-stringify/issues/338
~~No new tests or benchmarks.~~ The one added test causes the time to run the tests to increase from 2 to 7 seconds.
Benchmarks seem to go up or down a few percent, probably within the margin of error.
N/A

Fix minimizer renaming functions

---

index.js
test/oneof.test.js

Related issue: https://github.com/fastify/fast-json-stringify/issues/342

fix: unmatched type for value in oneOf should be ignored

---

bench.js
index.js

The current version of date formatting is constructing a bunch of new objects using Intl and is comparetively slow. The simply `toISOString` and `splice` show a local speed up of up to 300x in terms of formatting and should yield the same results.
The date tests use momentjs formatting as comparison, which seems to respect time zones, thus, I also respected the time zones.
Before change
> fast-json-stringify date format x 2,900 ops/sec ±1.19% (82 runs sampled)
After change
> fast-json-stringify date format x 1,608,371 ops/sec ±1.30% (89 runs sampled)
**x 555 faster**

perf: speed up date formatting by 555x

---

.github/workflows/benchmark.yml

I did the tests in my fork: https://github.com/RafaelGSS/fast-json-stringify/pull/3. 

chore: add benchmark setup

---

README.md

chore: add oneOf to docs

---

index.js
test/debug-mode.test.js

Uses `ajv.addSchema` to load all validation schemas while building the code instead of serializing the schema to an object literal that is eventually passed `ajv.validate`.
Could fix the memory leak discussed in #379

Use `ajv.addSchema` to load validation schemas at build

---

index.js

Not sure about the `randomUUID()` performance.
I would use something more basic as `Math.random()` or `crypto.randomBytes`.
Need to try it

chore: unnecessary stringify calls

---

index.js
package.json
test/typebox.test.js

This PR is exactly what https://github.com/fastify/fast-json-stringify/pull/378 does but without any unwanted linting /whitespace changes. 
@suyash-thakur, @mcollina 

Fix: Prevent buildObject to create recursive call without base condition #378

---

example.js

If you currently try to execute `example.js`, error `Cannot find module 'fast-json-stringify'` is thrown. To fix this, the import statement must be modified.

Fix example.js

---

.github/workflows/benchmark.yml

See https://github.com/fastify/fastify/pull/3832

ci(benchmark): revert to using `pull_request_target`

---

README.md
bench.js
index.js
test/array.test.js

This PR is a tentative approach at improving the behavior described in https://github.com/fastify/fastify/issues/3498. In short, for very large arrays (approx over 20k elements) the overhead introduced by `fast-json-stringify` becomes relevant and makes the stringifying process longer.
Closes https://github.com/fastify/fastify/issues/3498.
Some simple benchmarks were run both in order to better understand the issue and to understand the impact of the various approaches attempted at improving it.
A variable-length array with [similar spec as to the large one available in the linked issue](https://gist.github.com/wilkmaia/85f1e77316a00418abf6703c5ac664aa) was stringified using two approaches:
- `JSON.stringify` as baseline
- `fast-json-stringify`
Data on array length and time taken for the …

feat: add support for better handling with large arrays

---

index.d.ts
index.js
test/recursion.test.js

This PR should resolve inline `$id` references mentioned on issue https://github.com/fastify/fast-json-stringify/issues/410. This implementation adds an additional `schemaReferenceMap` which is used to collect schemas with `$id` observed during the build phase. These references are later resolved in subsequent calls to the `refFinder(...)` function.
Note: There is some overlap here with the existing `externalSchema` variable which I think may be trying to resolve specifically for anchor (or `#`) references (I'm entirely not sure). I have left the `externalSchema` implementation as is as a fall through. It was noted however that the `externalSchema` variable was `undefined` for the inline `$id` / …

Support inline $id references

---

.github/workflows/ci.yml
package.json

chalk v.4.1.2 is the last version that supports commonjs modules. we shouldn't upgrade to v5 #419

Revert chalk dev dependency version

---

benchmark/bench.js

Small objects with variables of different types is very unstable for benchmarking for some reason. I tried manually remove unused empty if block and it decrease performance. + the problems I described here https://github.com/fastify/fast-json-stringify/pull/416#issuecomment-1133928883. When we increase object size it become more stable.

benchmark: increase size of testing object

---

index.js
test/date.test.js

Right now date serialization can return 24 hours. "24:12:43". I'm not sure that this is expected.
That is the reason why ci fails sometimes.

fix: set 23 hour cycle

---

index.js
test/basic.test.js
test/patternProperties.test.js
test/required.test.js

fix: throw an error if cannot convert value to number

---

README.md

This PR fixes a typo.
`serialzied` -> `serialized`

chore: fix typo serialzied -> serialized

---

index.js
test/array.test.js
test/nullable.test.js

Depends on #437 
This PR fixed two bugs:
1. Add support for nullable large arrays.
2. Fix large array string serialization.
If we pass the `asString` function
https://github.com/fastify/fast-json-stringify/blob/4bec21e6ee6951879958247f0299b11a25490d19/index.js#L159
to this map as `mapFnName `
https://github.com/fastify/fast-json-stringify/blob/4bec21e6ee6951879958247f0299b11a25490d19/index.js#L1043
it will receive the array index as the second argument and will skip quotes

fix: large array serialization

---

index.js

oneOf and anyOf are processed with the same code.

refactor: combine oneOf and anyOf handlers

---

index.js
test/nestedObjects.test.js

There is possible to have a function names collision. I suggest not overcomplicating things and using only generated function names.

fix: generated function names collision

---

index.js
test/anyof.test.js
test/debug-mode.test.js
test/oneof.test.js

This problem is very similar to https://github.com/fastify/fast-json-stringify/issues/431#issuecomment-1138809786.
What should we do if none of oneOf/anyOf options match? Right now if it's an object it will set the null value, if it's an array it will skip the value.
This can be considered a significant change and can be landed in semver major release.

fix: throw an error if none of oneOf/anyOf options match

---

index.js
test/anyof.test.js

❗ Depends on BREAKING CHANGE PR #442
Fixed #325

fix: date/time ajv validation

---

index.js
test/additionalProperties.test.js
test/patternProperties.test.js
test/sanitize3.test.js

Object properties, additional object properties, and pattern object properties were processed by three different functions. I removed duplication. These three implementations had different ways to deal with array coercion. If it was an object property with array type it checked with Array.isArray function. If it was an additional or pattern property it didn't check but coerced to an array type in an unacceptable (IMHO) way.
Now it always checks the array typed value with Array.isArray function.
https://github.com/fastify/fast-json-stringify/blob/1c120dd71895e2b5c5b404268d6a9b16f399b4cb/test/additionalProperties.test.js#L161

refactor: use build value for additional and pattern properties

---

index.js
test/allof.test.js

fix: serializing schema with allOf option

---

index.js
test/allof.test.js
test/ref.test.js

❗BREAKING CHANGES
This PR uses ajv addSchema and getSchema methods for resolving json schema references. For this, we need to represent schema and external schemas in terms of json schema draft 7. 
I think it's a good opportunity to fix some issues.
First of all when we pass external schemas as an object.
```js
const externalSchemas = {
a: { type: 'number' },
b: { type: 'string' },
}
```
What do keys of the object mean in terms of json schema? Are they base URLs for these schemas? If so how should what should happen if we pass the key and $id?
```js
const externalSchemas = {
a: { $id: 'id1' },
b: { $id: 'id2' },
}
```

fix: use ajv for schema ref resolving

---

index.js

refactor: save additional functions in context array

---

README.md
ajv.js
index.js
serializer.js
test/standalone-mode.test.js

1. move `debugMode` in `mode` option.
2. provide `standalone` mode which people can create the code that can directly require and run
3. fixes #459 

feat: standalone mode

---

README.md
index.d.ts
index.js
standalone.js
test/standalone-mode.test.js
test/types/test.ts

This PR do not need to merge immediately.
We need to test each edge case before merging this PR.
1. It remove `fast-json-stringify` in `standalone` code.
2. It address the issue of `fast-json-stringify` generate custom json schema.
3. It update the types.

fix: standalone ajv schema

---

serializer.js

Since #441 , the `skipQuotes` branches are not used and not needed anymore because we use `ajv` to validate the dates.
mention @ivan-tymoshenko 

refactor: delete unreachable branches

---

index.js

Fixes this LGTM alert
https://lgtm.com/projects/g/fastify/fast-json-stringify/?mode=tree&ruleFocus=7900088

fix lgm alert: Useless assignment to local variable

---

.github/workflows/ci.yml
benchmark/bench-cmp-branch.js
package.json

benchmark-cmp-branch is broken, as inquirer 9.0.0 is now an ESM-Module, like latest chalk.
Instead of setting a lower version of inquirer and adding it into the blacklist of dependabot it like chalk I simply replaced inquirer with the less heavy cli-select and replaced chalk with basic ansi-codes for the color handling. I mean... after all it is only used for the benchmark.

fix benchmark-cmp-branch, remove chalk and inquirer

---

serializer.js
test/infinity.test.js

serializer.js - asNumber(), asInteger()

---

index.js
test/issue-479.test.js

fixes https://github.com/fastify/fast-json-stringify/issues/479
The issue:
after the merge of the `allOf` object, we lose the `$id`s of the merged objects, so it is not possible to call `ajv.validate` when one of the `allOf` objects contains an `anyOf` or `allOf` item.
This fix adds a reference to the merged object to use it as a validator.
Any better ideas?

fix: reference after merge allOf

---

index.js
test/ref.test.js

Fix #481
Fix https://github.com/fastify/fastify/issues/4092
#480 sets merged schema as a location, but doesn't set json pointer to the root of this merged schema.

fix: reset json pointer in merged allOf schema

---

index.js
package.json

I have just one worry: @fastify/deepmerge has prototype protection handling. What happens if in the json schema an type: object has the key prototype or constructor? It would mean that those keys are not merged/carried over. should we change deepmerge to have an option where we create Objects by using Object.create(null) so that a prototype pollution is not possible?

perf: replace deepmerge npm-package with @fastify/deepmerge

---

ajv.js
index.js
serializer.js
test/date.test.js

fix: string date format validation

---

index.js

use hasOwnProperty from Object.prototype

---

index.js
test/typesArray.test.js

Fix #492 
I think that this is a good opportunity to discuss this check. It says that if an object has a defined custom `toString` method, we should validate it as a string. There are two points why I think this is a bad check.
1. We don't coerce types during type validation because, otherwise, everything can be coerced to the string. Numbers and booleans also have the toString method, but we don't count them as a string type.
2. Ajv also does not use type coercion during schema validation, so the `toString` method won't be checked if you have anyOf/oneOf instead of a type array.
I want to drop this check in some major release of FJS/Fastify. I would like to heat your thoughts about it.

fix: toString method validation check

---

benchmark/bench.js
example.js
index.js
test/const.test.js

As per issue https://github.com/fastify/fast-json-stringify/issues/502, when using a const schema, the performance degrades. This is the continuation of #505.
Pre PR
Post PR
This PR supports nullable values:
```javascript
test('schema with const string and no input', t => {
t.plan(2)
const schema = {
properties: {
foo: { const: 'bar' }
}
}
const validate = validator(schema)
const stringify = build(schema)
const output = stringify({})
t.equal(output, '{}')
t.ok(validate(JSON.parse(output)), 'valid schema')
})
```
Or it coerces the value to the const property if it is required
```javascript
test('schema with const string and no input but required property', t => {
t.plan(2)
const …
```

Improve performance for const schemas

---

index.js
package.json
ref-resolver.js
test/ref.test.js

Fix #506 
I want to return a custom JSON schema reference resolver with some changes. It will only resolve JSON schema references only at serializer compilation time. All refs used for validation still will be resolved by Ajv. It's a proof of concept. I need to read the JSON schema doc carefully before merging it.

refactor: create json schema ref resolver

---

index.js

My bad, I've badly rebased #504 on #511. It doesn't fail because it is an unreachable code now.

refactor: remove const validation branch

---

index.js

Even if #517 is not an issue, we don't need to clone and modify the schema here. It's enough to reassign the variable.

refactor: remove array items schema cloning

---

index.js
serializer.js

I'm sorry that there are so many changes. Most of them are decomposition into functions without changes. This PR does two things:
1. Handles nullable property in one place instead of checking it all over the code.
2. Optimize handling multitype schemas. 
I can't separate these two changes. They are related to each other.

refactor: handle nullable schema in one place

---

index.js
test/array.test.js

Type checking in this place is not only unnecessary (FJS is not a validator), it blocks type coercion for array items for no reason.

fix: remove array items type checking

---

index.js
test/debug-mode.test.js

fix: return Serializer instance in debug mode

---

index.js
test/if-then-else.test.js

We have to check for if/then/else all schemas. Not only objects.

fix: apply if/then/else check for any schema

---

index.js
test/array.test.js

Adds a unit test to check if 'invalid' throws an error (increasing coverage). 
Fixes the error output. 

add test for invalid value for largeArrayMechanism

---

.taprc

IMHO We dont need the coverage of the automatically generated schema-validator.js 

ignore automatically generated schema-validator.js from coverage, increase required coverage

---

index.js
test/anyof.test.js

This will optimize a cold start for those schemas that have validation parts (anyOf, oneOf, if/then) and others external schemas in the context. 
\+ It might help with resolving schema conflicts in the future for #508.

perf: add only required schemas to the validator

---

test/if-then-else.test.js

fix ajv strict warnings in if/else-tests

---

package.json

Both `lint` and `test:lint` do the same thing. Just use `lint` to keep inline with other Fastify repos.

chore(package): remove duplicate script

---

index.js
lib/location.js
test/allof.test.js

fix: merged schemas reference resolving

---

lib/serializer.js

Do you want some perf upgrades? I've got something for you.

perf: use regexp in string escaping

---

index.js
lib/location.js
lib/ref-resolver.js
test/anyof.test.js

Fix #555 
Fix https://github.com/fastify/fastify/issues/4390

fix: track schema dependecies

---

README.md

Let's make it clear that fast-json-stringify is not a validator and the caller takes all the responsibilities on the safety of the data being rendered.

fast-json-stringify is not a validator

---

index.js
test/typesArray.test.js

When we attempt to stringify Object as an Array, the Object does not displayed properly (`'[object Object]'`). To simplify debugging process, we should display better error message to pinpoint where the problem using `schemaRef` property of `location` object.
Example:
```
// Schema
const schema = {
properties: {
arr: {
type: 'array',
items: {
type: 'number'
}
}
}
};
const stringify = build(schema);
stringify({ arr: { foo: 'hello' } });
```
Original:
```
{
"type": "TypeError",
"message": "The value '[object Object]' does not match schema definition."
}
```
Proposed:
```
{
"type": "TypeError",
"message": "The value of '#/properties/arr' does not match schema definition."
}
```

fix: fix error message when type is array and object is object

---

index.js

Why storing the result in json variable, if never used again?

avoid intermediate variable

---

index.js
test/array.test.js

If Array as additionalItems undefined or false, then it generates following code:
```
if (arrayLength > undefined) {
throw new Error(`Item at undefined does not match schema definition.`)
}
```
This does not make any sense. Ajv is ignoring additionalItems if items is not an array. So we just add the additionalItems check if the index is an Array of Schemas

Array should only have "length"-check if items is an Array

---

index.js
test/any.test.js
test/array.test.js
test/multi-type-serializer.test.js

This is a follow up from #569 by @yukha-dw
I previously opened a Report to hackerone, as I feared that the current implementation could be a potential security issue. But as it got closed as not applicable, I guess I can safely propose this PR :).
So instead of calling JSON.stringify to show the value of an Object, we just show the schema location. As such, we avoid, that we have to potentially stringify a JSON, which we didnt want to stringify in the first place. 

expose only location instead of Object value

---

test/allof.test.js

add unit test for allOf, where types, format and nullable missmatch

---

index.js
test/patternProperties.test.js

We can never catch that error because ajv is already validating that pattern properties are valid regex values. 
improves code coverage. 

invalid value for patternproperties are validated by ajv

---

lib/serializer.js
test/date.test.js
test/string.test.js

improve coverage of serializer.js to 100%

---

lib/standalone.js

When we generate a standalone serializer we pass the whole object into the serializer (e.g. `{ mode: 'standalone' }`) which makes no sense. 
This PR basically just passes throuh the rounding option, if set. 

only pass rounding option to serializer of standalone

---

lib/serializer.js

fast path is now the assumption, that it is checking for a number and instead of using Number.isFinite and co. it tries to avoid those function calls.

improve performance of asInteger serializer

---

lib/serializer.js

before: 
```js
{"n1":1,"n2":null}
number x 43,047,096 ops/sec ±1.45% (183 runs sampled)
```
after: 
```js
node bench
{"n1":1,"n2":null}
number x 1,253,340,543 ops/sec ±0.11% (195 runs sampled)
```
This is my benchmark:
```js
'use strict'
const Benchmark = require('benchmark')
Benchmark.options.minSamples = 100
const suite = Benchmark.Suite()
const FJS = require('.')
const stringify = FJS({
properties: {
n1: { type: 'number' },
n2: { type: 'number' },
}
})
// const stringify = require('./serialize')
const input = {
n1: 1,
n2: Infinity
}
console.log(stringify(input))
suite
.add('number', () => {
stringify(input)
})
.on('cycle', (event) => {
console.log(String(event.target))
})
.on('complete', () => {})
.run()
```
and the [Code of …

improve performance of asNumber

---

index.js

I dont know why we use var for those variables, because in the generated code we use const and let in other places.
It reduces some pressure on the GC if we avoid some intermediate string variables. 

avoid intermediate strings. use const and let

---

index.js

Well, the `dependenciesName` array is actually only needed for debug mode. Dont need that always

avoid generation of intermediate array

---

index.js

Properly encapsulate the whole state of the builder. Preparation for further changes like implementing a possible strict mode as discussed in #579 

instead of global variables create context object and pass it as parameter

---

lib/serializer.js
test/integer.test.js

I forgot that the | 0 trick only handles numbers up to 2^32 properly

use Number.isInteger instead of bitwise operation

---

index.js
test/integer.test.js

#582 
Improving test coverage part 1

chore: 582 - improving test coverage

---

test/ref.test.js

improve statements coverage of ref-resolver to 100%

---

index.js

Fixed a typo `variabe` -> `variable`.

docs: fix typo

---

benchmark/bench.js
lib/serializer.js
test/basic.test.js

running only the first 4 benchmarks with maxSamples 100 (or else it takes gazillion years
before:
```sh
short string............................................. x 27,631,407 ops/sec ±0.44% (192 runs sampled)
short string with double quote........................... x 8,093,221 ops/sec ±0.59% (191 runs sampled)
long string without double quotes........................ x 26,659 ops/sec ±0.28% (193 runs sampled)
long string.............................................. x 11,697 ops/sec ±0.19% (192 runs sampled)
```
after:
```sh
short string............................................. x 43,111,798 ops/sec ±0.96% (187 runs sampled)
short string with double quote........................... x 13,393,581 ops/sec ±0.39% (191 runs sampled)
long string without double quotes........................ …
```

improve perf of asString

---

.github/workflows/benchmark.yml
benchmark/bench-thread.js

It doesnt make sense to make a benchmark accross libs. What we need is the benchmark between branches.
This changes the benchmark to benchmark between two branches when adding the benchmark label.
Also reducing the maxSample to 100, as doing 500 samples takes a million years and is not more reliable.

improve benchmark workflow

---

index.js
test/allof.test.js

Fixes https://github.com/fastify/fastify/issues/4920

fix: support anyOf inside allOf

---

benchmark/bench.js
index.js

With this PR we first handle all the required fields. If the field is required, it will throw early. 

process required first

---

README.md
benchmark/bench-cmp-branch.js
benchmark/bench-thread.js
benchmark/bench.js
build/build-schema-validator.js
examples/server.js
index.js
test/standalone-mode.test.js
test/webpack.test.js

See https://github.com/fastify/fastify-static/pull/407

perf: use `node:` prefix to bypass require.cache call for builtins

---

index.js
test/const.test.js

I found a bug in serialization function composition logic where if I have const schema that contains `'` character it doesn't escape that character properly. I fixed this case by escaping all `'` characters in used produced JSON.

Serializing const type with `'` character

---

README.md
benchmark/bench-cmp-branch.js
benchmark/bench-thread.js
benchmark/bench.js
build/build-schema-validator.js
examples/server.js
index.js
test/standalone-mode.test.js
test/webpack.test.js

This reverts commit 4073e5b6c9b2f4c6b4a3cea1f0f1d6f0ba89e769.
Signed-off-by: Matteo Collina <hello@matteocollina.com>
Fixes https://github.com/fastify/fast-json-stringify/issues/659

Revert "perf: use `node:` prefix to bypass require.cache call for builtins (#644)"

---

index.js

We dont need crypto randomUUID, because we are cool. We use an internal counter and a fsj specific prefic to generate the schema.id. 
@Ethan-Arrowood 
@inlet

feat: replace uuid with prefixed string with schemaIdCounter

---

index.js
test/array.test.js

Closes https://github.com/fastify/fast-json-stringify/issues/662
- changed `buildTest` to compare parsed-FJS vs parsed-JSON because some things (like `Date`, and in general anything with `.toJSON`) cannot be parsed back after stringification
- removed `!(${input} instanceof Date` check beacuse earlier we already do `|| instanceof Date`
- `toString` check is giga questionable, real `JSON.stringify` behavior ignores `toString` and instead uses `toJSON`, see:
- [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description)
- try in REPL: `JSON.stringify({toString:() => 'json'})` vs `JSON.stringify({toJSON:() => 'json'})`

fix: consistently handle string in array

---

README.md
index.js
test/basic.test.js
test/toJSON.test.js
test/typesArray.test.js

This PR is related to issue #669. The changes applied bring an error being thrown with a somewhat descriptive message whenever a non-nullable schema of type 'object' validates against a null value.
Before this change, the generated code would ignore checks on the input value, trying to access properties on a null value which of course results in the application throwing `cannot read <prop> of undefined`. To address this we simply add a check on the function head and throw a meaningful error if needed.
- [] documentation is changed or added

fix: non-nullable schema receiving null input does not coerce for default types on object and arrays

---

index.js
lib/location.js
lib/merge-schemas.js
package.json
test/allof.test.js
test/anyof.test.js
test/if-then-else.test.js

This PR adds a proper schema merging for different cases:
- root schema + oneOf/anyOf subschema 
- root schema + all allOf subschemas
- root schema + then schema; root schema + else schema
Fix #648
Fix #642

fix: update internal schema merging

---

index.js
test/allof.test.js
test/required.test.js

It removes a check before adding a comma if there are required props. Which gives you around 8-10% perf boost if object has at least one required property.
_Before:_
_After:_

perf: optimize required props serialization

---

index.js
lib/location.js
lib/merge-schemas.js
package.json
test/allof.test.js
test/anyof.test.js
test/if-then-else.test.js
test/required.test.js

fix: merged schemas caching

---

types/index.d.ts
types/index.test-d.ts

- Fixes #682
This fixes the ability for `fast-json-stringify` to coerce Dates into strings and BigInts into numbers. These type tests weren't having any effect before: when schemas are declared like
```ts
// Number schemas
const schema1: Schema = {
type: 'number'
}
const schema2: Schema = {
type: 'integer'
}
build(schema1)(25)
build(schema2)(-5)
```
`schema1` and `schema2` are typed simply `Schema`, so none of the nice type inference is triggered and you can pass any argument to the method, like
```ts
build(schema1)({ xyz: 1 })
```
And there will be no type error. This adds some duplication because the two options that I know of are either adding `as const` to the end of each schema declaraction, or using a literal. `as const` doesn't work in this situation because it makes the type …

Fix coercion types

---

README.md
benchmark/bench.js
index.js
lib/serializer.js
test/basic.test.js
test/string.test.js

This PR add the 'unsafe' string format. By default, `fast-json-stringify` escapes all strings. With the 'unsafe' format, the string isn't escaped. This has a potentially dangerous security issue. You can use it only if you are sure that your data doesn't need escaping. The advantage is a significant performance improvement.
Usage into the JSON schema
```javascript
const stringify = fastJson({
title: 'Example Schema',
properties: {
'code': {
type: 'string',
format 'unsafe'
}
}
})
```
benchmark (safe VS unsafe):
```
short string............................................. x 14,605,189 ops/sec ±3.85% (157 runs sampled)
unsafe short string...................................... x 693,266,405 ops/sec ±3.05% (187 runs sampled)
long string without double …
```

feat: unsafe string format

---

lib/serializer.js

Comparing more values in a single if statement has a little performance hit instead of make multiple if statement. In general, combining multiple comparisons into one if statement might result in slightly better performance due to reduced overhead from evaluating conditions and executing multiple control flow structures. This is because combining conditions can reduce the number of times the JavaScript engine has to evaluate expressions and jump between different parts of the code.
benchmark (master VS PR)
```
short string............................................. x 16,634,103 ops/sec ±2.06% (182 runs sampled)
short string............................................. x 18,920,179 ops/sec ±1.07% (184 runs sampled)
```
PR seems better!
and the [Code of …

chore: performance improvement on asStringSmall

---

index.js
lib/serializer.js

asString is Polymorphic/Megamorphic because accept more type (string, date, regex, null)
So let’s spend some more time defining this.
- Monomorphic: If function arguments are always the same type.
- Polymorphic: If function arguments are few (four or fewer) different type.
- Megamorphic: If function arguments are more than four type.
In short: functions that are invoked with the same types over and over again are optimized in the JIT compiler, hence faster.
**Megamorphism asString (actual code)**
```
short string............................................. x 14,825,973 ops/sec ±4.07% (156 runs sampled)
short string with double quote........................... x 6,743,956 ops/sec ±4.15% (156 runs sampled)
long string without double quotes........................ x 3,662 ops/sec ±5.18% …
```

fix: make asString monomorphic  and trigger V8 optimization

---

lib/serializer.js

Only use the regular expression `STR_ESCAPE` for shorter input. The overhead is otherwise too much.
Before
```
long string without double quotes........................ x 9,395 ops/sec ±6.66% (136 runs sampled)
long string.............................................. x 7,237 ops/sec ±2.61% (175 runs sampled)
```
After
```
long string without double quotes........................ x 13,095 ops/sec ±1.26% (184 runs sampled)
long string.............................................. x 13,734 ops/sec ±1.65% (179 runs sampled)
```

chore(perf): only use the regular expression for shorter input

---

lib/serializer.js

The regex 
```
[\u0000-\u001f\u0022\u005c\ud800-\udfff]|[\ud800-\udbff](?![\udc00-\udfff])|(?:[^\ud800-\udbff]|^)[\udc00-\udfff]
```
can be 
```
[\u0000-\u001f\u0022\u005c\ud800-\udfff]
```
The first part of alternation (`[\u0000-\u001f\u0022\u005c\ud800-\udfff]`) will match anything that might have been matched by the second (`[\ud800-\udbff](?![\udc00-\udfff])`) and third part (`(?:[^\ud800-\udbff]|^)[\udc00-\udfff]`).
I have made this simple online test for play with both rule (https://jsfiddle.net/nd84e7fz/):
```js
const NEW = /[\u0000-\u001f\u0022\u005c\ud800-\udfff]/;
const OLD = /[\u0000-\u001f\u0022\u005c\ud800-\udfff]|[\ud800-\udbff](?![\udc00-\udfff])|(?:[^\ud800-\udbff]|^)[\udc00-\udfff]/;
const str1 = '\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r' + …
```

perf: fast regex check on string

---

lib/serializer.js

With this PR when a  `"` or `\` is into the string, the if statement for surrogate check is not called. This is a little performance improvment
benchmark with focus on small string
master
```
short string............................................. x 23,456,041 ops/sec ±0.52% (190 runs sampled)
short string with double quote........................... x 13,475,336 ops/sec ±0.55% (189 runs sampled)
```
PR
```
short string............................................. x 23,641,068 ops/sec ±0.57% (191 runs sampled)
short string with double quote........................... x 13,703,071 ops/sec ±0.43% (187 runs sampled)
```

perf: reduce if statement call on `"` and `\` (micro-optimization)

---

lib/serializer.js

perf: reduce if statement for `NaN` (micro-optimization)

---

.github/workflows/ci.yml
.taprc
package.json

Ref: https://github.com/fastify/fastify/issues/5116
- Removed the `ts` and `jsx` which are replaced by disabling the `!@tapjs/typescript` plugin. 
-  `branches`, `functions`, `lines` and  `statements` where dropped in v18 -> https://node-tap.org/changelog/
- `nyc` were also dropped in v18
- `coverage` is enabled by default in v18, disabling them via `disable-coverage: true`
CC: @simoneb

Update for Fastify v5

---

index.js

Caching the value of `obj[key]` into a variable instead of continue access to object
PR
```
short string............................................. x 22,806,425 ops/sec ±0.47% (191 runs sampled)
unsafe short string...................................... x 1,027,602,256 ops/sec ±0.34% (191 runs sampled)
short string with double quote........................... x 13,276,009 ops/sec ±0.33% (190 runs sampled)
long string without double quotes........................ x 15,398 ops/sec ±0.24% (192 runs sampled)
unsafe long string without double quotes................. x 1,011,926,548 ops/sec ±0.30% (188 runs sampled)
long string.............................................. x 15,779 ops/sec ±0.22% (193 runs sampled)
unsafe long string....................................... x 1,018,123,202 …
```

Performance: Cache obj[key] access into 

---

index.js
test/array.test.js

This is a small breaking change so should be released with a Fastify v5.
Take a look at: https://github.com/fastify/fast-json-stringify/pull/524
@mcollina @gurgunday What branch should I select to merge to? `next`?

feat: drop array items type checking

---

index.js

Just removed a useless jsonOutput variable
```
Checking out "master"
Execute "npm run bench"
> fast-json-stringify@5.14.1 bench
> node ./benchmark/bench.js
short string............................................. x 23,463,000 ops/sec ±0.67% (190 runs sampled)
unsafe short string...................................... x 1,068,252,499 ops/sec ±0.38% (191 runs sampled)
short string with double quote........................... x 13,965,895 ops/sec ±0.46% (191 runs sampled)
long string without double quotes........................ x 15,826 ops/sec ±0.51% (191 runs sampled)
unsafe long string without double quotes................. x 1,063,725,876 ops/sec ±0.45% (188 runs sampled)
long string.............................................. x 16,194 ops/sec ±0.41% (192 runs sampled)
unsafe long …
```

perf: removed jsonOutput variable because is useless

---

index.js

```
npm run bench:cmp
> fast-json-stringify@5.14.1 bench:cmp
> node ./benchmark/bench-cmp-branch.js
Select the branch you want to compare (feature branch):
cache-str
Select the branch you want to compare with (main branch):
master
Checking out "cache-str"
Execute "npm run bench"
> fast-json-stringify@5.14.1 bench
> node ./benchmark/bench.js
short string............................................. x 16,870,462 ops/sec ±2.49% (173 runs sampled)
unsafe short string...................................... x 724,139,578 ops/sec ±0.41% (186 runs sampled)
short string with double quote........................... x 8,446,363 ops/sec ±0.98% (187 runs sampled)
long string without double quotes........................ x 11,556 ops/sec ±0.44% (191 runs sampled)
unsafe long string without double …
```

perf: cache json strings into const

---

index.js
test/sanitize7.test.js

closes https://github.com/fastify/fast-json-stringify/issues/715

fix: escape single quote when building error message for required property
