README.md
example.js
index.js
test.js

Added support for `patternProperties`.
See discussion in #5 .

Pattern properties support

---

README.md
index.js
test/basic.test.js

Correctly escape as for the spec.

---

index.js

Correctly escape regex string

---

index.js
test/additionalProperties.test.js

Optional properties support

---

README.md
index.js
package.json
test/long.test.js

Support for long integers

---

index.js
test/additionalProperties.test.js

Fixes my problem: https://github.com/fastify/fast-json-stringify/issues/24#issuecomment-302866856

Allow specifying deep additionalProperties=true

---

README.md

Note that uglify is unnecessary on node 8.3.0

---

index.js
test/allof.test.js

Respond to issue #64 
Feel free to comment and argue, I don't open PR often.

Add a forEach to test each schema when there is an allOf

---

README.md
index.js
test/if-then-else.test.js

Implement nested if then else as the test explains
https://github.com/fastify/fast-json-stringify/blob/0f3e9726c141de6dea10feba9717b51967973bf9/test/if-then-else.test.js#L31-L67
NB: the developer shouldn't mention the property twice

Nested if then else

---

README.md

script log result can be produce in https://npm.runkit.com/fast-json-stringify
```js
var fastJson = require("fast-json-stringify")
const stringify = fastJson({
'type': 'object',
'properties': {
},
'if': {
'properties': {
'kind': { 'type': 'string', 'enum': ['foobar'] }
}
},
'then': {
'properties': {
'kind': { 'type': 'string', 'enum': ['foobar'] },
'foo': { 'type': 'string' },
'bar': { 'type': 'number' }
}
},
'else': {
'properties': {
'kind': { 'type': 'string', 'enum': ['greeting'] },
'hi': { 'type': 'string' },
'hello': { 'type': 'number' }
}
}
})
console.log(stringify({
kind: 'greeting',
foo: 'FOO',
bar: 42,
hi: 'HI',
hello: 45
}))
console.log(stringify({
kind: 'foobar',
foo: 'FOO',
bar: 42,
hi: 'HI',
hello: 45
}))
```
result should be
```
{"kind":"greeting","hi":"HI","hello":45} …
```

error console.log result in readme

---

index.js
test/invalidSchema.test.js

Closes #139 
Resulting error will look like:
```
Error: "mySchema" schema is invalid: ...
```

feat: add schema name to error

---

README.md

Updated benchmarks

---

index.js
test/typesArray.test.js

Corrects integer handling

---

test/typesArray.test.js

Add more tests

---

README.md
index.js
test/missing-values.test.js
test/typesArray.test.js

Make integer handling consistent for type arrays as discussed in #145

Make integer/number handling consistent for type arrays

---

index.js
test/anyof.test.js

Fix serialization of schemas using nested anyOfs containing multiple objects, which is the underlying issue of #155.

Fix nested anyOfs using objects

---

index.js
test/anyof.test.js
test/sanitize.test.js

This PR is the coordinated work on myself and @phra to make fast-json-stringify more robust in case of untrusted user input. This does not make it safe to use (bugs and vulns can always be there), but it covers all the cases we could think of.

Sanitize input so it's safer

---

index.js
test/ref.test.js

This PR complete https://github.com/fastify/fastify/pull/1882

Fix relative ref

---

index.js
test/if-then-else.test.js

Issue #208 making else non mandatory

---

.github/workflows/ci.yml
README.md

Issue #203 - Move to Github Actions

---

.dependabot/config.yml
README.md
package.json

As titled, greenkeeper is shutting down.

Drop greenkeeper for dependabot

---

README.md
index.js
test/debug-mode.test.js

Closes #180 
I'm not sure about `global.ajv` setup to let it works in some cases (checkout the last test in the new file)
Any ideas about how to improve this "debug mode"? 👍

add debug mode

---

index.js
test/allof.test.js

Support $ref in allOf

---

index.js
test/allof.test.js
test/anyof.test.js
test/ref.test.js
test/required.test.js

feat: add required check for object key not in properties

---

README.md

Adds additional example for *anyOf* docs. Resolves #230 and compliments #235.

Adds additional anyOf example for objects.

---

test/allof.test.js
test/any.test.js
test/anyof.test.js
test/array.test.js
test/clean-cache.test.js
test/nestedObjects.test.js
test/oneof.test.js
test/ref.test.js
test/regex.test.js
test/required.test.js
test/typesArray.test.js
test/unknownFormats.test.js

remove bad pattern from tests suites

---

index.js
test/additionalProperties.test.js

fix enum without type

---

index.js
test/defaults.test.js

fix multi default

---

index.js

Following https://github.com/fastify/fast-json-stringify/pull/256 , added minor cleaning.
Delete unecessary string allocation.

fix: minor cleaning

---

index.js
test/any.test.js

Checks if key value is undefined in isEmpty function

---

.github/workflows/ci.yml

Add Node v14 to CI

---

index.js
test/typesArray.test.js

Ref #193 
Details https://github.com/fastify/fast-json-stringify/issues/193#issuecomment-703804249

feat: simultaneously test example

---

bench.js
package.json

Removed as json-strify repository is not Open Source.

Drop json-strify

---

README.md

add options paragraph

---

README.md
package.json

With issue #205 I decided to set up a run Kit  Example for this fast-json-stringify

Runkit Example Fix

---

index.js
test/side-effect.test.js

Fixes https://github.com/fastify/fastify/issues/2914
Follow up PR https://github.com/fastify/fastify/pull/2925

fix side effect on items $ref

---

.taprc
package.json
test/allof.test.js
test/any.test.js
test/anyof.test.js
test/array.test.js
test/basic.test.js
test/debug-mode.test.js
test/defaults.test.js
test/inferType.test.js
test/integer.test.js
test/nestedObjects.test.js
test/nullable.test.js
test/oneof.test.js
test/ref.test.js
test/required.test.js
test/sanitize.test.js
test/side-effect.test.js
test/typesArray.test.js

Migrating to node-tap 15 and fixing deprecated methods

feat: move to tap 15

---

.github/workflows/ci.yml
README.md

chore: doc and ci updates

---

example.js

I was getting `SyntaxError: Strict mode code may not include a with statement` this error on RunKit so I thought to update `example.js`.

modifying run kit example

---

index.js
test/anyof.test.js
test/oneof.test.js

Here is a PR to fix https://github.com/fastify/fast-json-stringify/issues/325
Not sure this is the best implementation so far.

fix: ajv validation oneOf anyOf

---

README.md
index.js
test/anyof.test.js

fix: #330 
Extra quotes were added when using the test serializer leading to the null fallback

fix: #330 extra quotes on string test

---

index.js
test/integer.test.js

fix round internal integer

---

.github/workflows/ci.yml
.taprc
README.md
example.js
index.js
package.json
test/allof.test.js
test/any.test.js
test/anyof.test.js
test/array.test.js
test/basic.test.js
test/date.test.js
test/debug-mode.test.js
test/defaults.test.js
test/enum.test.js
test/inferType.test.js
test/integer.test.js
test/nestedObjects.test.js
test/nullable.test.js
test/oneof.test.js
test/ref.test.js
test/required.test.js
test/requiresAjv.test.js
test/sanitize.test.js
test/side-effect.test.js
test/typesArray.test.js
test/webpack.test.js

This a merge of main into next
- solved conflicts
- fix new `format` tests that were failing due to the `ajv-format` missing see commit 6a805de
Unblock #353 

Marge main into next

---

index.js

The trick here is we check only the last char of the `result.code` and not the complete json string.
Master:
```
fast-json-stringify array x 334 ops/sec ±0.41% (89 runs sampled)
```
This Pr:
```
fast-json-stringify array x 3,813 ops/sec ±3.93% (86 runs sampled)
```

feat: performance array improvement by 11x

---

README.md
index.js

Moar speed in arrays

---

index.js
test/recursion.test.js

Resolves https://github.com/fastify/fast-json-stringify/issues/365.
- This probably needs more tests.

Add support for recursive references in object types

---

index.js
test/allof.test.js

Fix for https://github.com/fastify/fast-json-stringify/issues/368.

fix: allOf withing $ref within allOf (fastify#368)

---

.github/workflows/ci.yml

Drop Node 10, 12, 13

---

index.js

Since `fast-json-stringify` works with JSON Schema Draft 7 we should point to the specification of Draft 7 and not to the latest version.

Change link to JSON Schema Draft 7 specification

---

index.js
package.json

Use `fast-uri` to speed up cold start.
- master: `FJS creation 10,351 ops/sec`
- branch: `FJS creation 11,023 ops/sec`

feat: use fast-uri

---

README.md

Just some very small fixes. I have added 2 commas and fixed a `href` in the TOC.

some small fixes

---

.github/workflows/benchmark.yml

See https://github.com/fastify/fastify/pull/3828

ci(benchmark): reduce workflow permissions

---

benchmark/bench-cmp-branch.js

Change default bench branch to master

---

index.js

I don't know what this should do. It looks like it always empty block.

remove unused rendered variable

---

index.js

Remove Intl time formatter

---

benchmark/bench.js

benchmarks: add date/time test cases

---

index.js
test/nullable.test.js

fix: return serialized null value as string

---

index.js

Spreading loop is working faster and it looks cleaner.

refactor: spread loop of object required properties

---

index.js
test/date.test.js
test/nullable.test.js

fix: add nullable date/time support

---

index.js

refactor: remove unused isArray buildValue argument

---

index.js
test/typesArray.test.js

fix: throw an error if none of types matches

---

index.js

Depends on #455
Return context function if it already exists instead of creating a new function that calls the original one.

refactor: return context function if schema exists

---

index.js
test/ref.test.js

Fix https://github.com/fastify/fastify/issues/4083#
Fix https://github.com/fastify/fast-json-stringify/issues/242

fix: input schemas mutation

---

index.js
test/if-then-else.test.js

fix: remove nested if/then duplicate serialization

---

serializer.js
test/Infinity.test.js

serializer.js - asNumber

---

index.js
test/ref.test.js

Fix https://github.com/fastify/fastify/issues/4108

fix: set hash sign as default json pointer

---

index.js
test/basic.test.js

fix: serialize schema with boolean type

---

test/nullable.test.js

Close #388
#388 was fixed in one of the refactoring PR. This PR adds a test for it.

test: add test for issue #388

---

test/nullable.test.js

Close #342
Issue #342 was fixed by #445. This PR adds a test that reproduces the test case.

test: add test for issue #342

---

test/nullable.test.js

Close #246
#246 was fixed in one of the refactoring PR. This PR adds a test case from the issue.

test: add test for issue #246

---

.github/workflows/benchmark.yml

ci(benchmark): remove eol node 12 from test matrix, add node 18

---

index.js

refactor: remove unreachanble condition branch

---

index.js

The empty schema handler is the same as the default handler.

refactor: remove empty schema handler

---

test/date.test.js

test: add test for issue #491

---

README.md
index.js
test/toJSON.test.js

@bmenant I've taken your tests from #414 (except two). Can you take a look at this PR?
All meaningful changes are here: https://github.com/fastify/fast-json-stringify/compare/add-tojson-function-handler?expand=1#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R877. All other is necessary refactoring.

fix: check all types for toJSON function

---

index.js
lib/standalone.js

perf: add schemas to the validator only if they are needed

---

.github/workflows/ci.yml
.taprc
package.json

right now the coverage is of and it is difficult to understand if all the improvements that this module is receiving are well tested or not

chore: turn on light coverage

---

index.js
test/ref.test.js

fix: resolving ref for object property with default value

---

index.js

refactor: refactor and optimize extra properties serializer

---

index.js

refactor: remove duplicate ref resolving in object serializer builder

---

index.js

shaving some yoctoseconds.... I guess.

use sanitized instead of stringifying again

---

lib/serializer.js

well. probably v8 optimizes, maybe not. pre-computing is anyway the way to go.

pre-compute empty string

---

index.js
test/array.test.js
types/index.d.ts
types/index.test-d.ts

improve mechanics and test coverage for largeArraySize-option

---

package.json

well. we dont require them anywere in the code

remove semver and proxyquire dev dependencies

---

.taprc
package.json

Streamline with all the other projects

move tap options into .taprc

---

test/ref.test.js

improve test coverage of ref-resolver to 100%

---

index.js

Well. This PR improves the performance of the creation. But dont ask me why...
before:
```sh
npm run benchmark
> fast-json-stringify@5.5.0 benchmark /home/uzlopak/workspace/fastify-org/fast-json-stringify
> node ./benchmark/bench-cmp-lib.js
FJS creation x 5,829 ops/sec ±1.54% (88 runs sampled)
```
after:
```sh
npm run benchmark
> fast-json-stringify@5.5.0 benchmark /home/uzlopak/workspace/fastify-org/fast-json-stringify
> node ./benchmark/bench-cmp-lib.js
FJS creation x 9,164 ops/sec ±1.48% (90 runs sampled)
```

improve perf of creation

---

index.js

branchless addComma

---

index.js

Probably highly subjective PR. 

sort objectKeywords by probability

---

benchmark/bench.js
index.js

Doubled the speed of the provided benchmark case
Thank you for your pull request. Please provide a description above and review
the requirements below.
Bug fixes and new features should include tests and possibly benchmarks.
Contributors guide: https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md
By making a contribution to this project, I certify that:
* (a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
* (b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open …

avoid main encapsulation for simple object

---

lib/serializer.js

improve asString performance

---

lib/serializer.js

avoid implicit conversion of null in serializer

---

README.md
index.js
lib/serializer.js
lib/standalone.js
lib/validator.js
package.json

feat: export standalone dependencies

---

.github/workflows/benchmark.yml

Node 20 becomes active LTS on 2023-10-24, so preemptively making a PR for it now.

ci(benchmarks): add node 20 to test matrix

---

.github/workflows/benchmark.yml

fix benchmark.yml

---

examples/example.js

chore(examples): add missing `use strict` directive

---

lib/ref-resolver.js

See https://github.com/fastify/fastify/pull/5057

perf(lib/ref-resolver): optimize split param

---

index.js
test/allof.test.js

Fix allOf with $ref property
